### ISSUE TITLE
[TIP] Issue에서 branch 파는 방법

### ISSUE THREAD

**Issue by suhyun113** [HICURE/HICURE#11]
## Issue에서 Branch 파는 방법

앞으로 branch를 팔 때, 이슈에서 파는 걸로 통일합시다!
branch를 팔 때는 페이지 단위로 하며, 필요할 때마다 이슈를 먼저 작성하면 됩니다.

**📌이슈 작성 방법**
1. 우측 상단의 초록색 New Isuue 버튼을 클릭합니다.
![image](https://github.com/user-attachments/assets/1f996122-dd84-4df3-962e-958d0b8a8c35)
2. 자신이 하고자 하는 작업에 맞게 Conflict 또는 Feature 선택합니다.
3. 작업 사항 작성 : 자신이 작업하고자 하는 페이지를 어떻게 구현할지 간단하게 작성합니다.
![image](https://github.com/user-attachments/assets/153e3317-0cfb-440e-bfba-bad937b134ad)
4. Todo 작성 : 페이지를 구현하면서 자신이 확인하기 쉽도록 체크박스를 만들어 어떤 작업을 해야하는지 세부적으로 나누면 됩니다. 자세하게 해도 되고 간단하게 해도 됩니다.
5. 오른쪽의 라벨을 설정합니다. Assignees는 이 이슈를 올리는 자신을 선택하고, Labels는 작업 내용과 자신의 이름을 선택합니다.
![image](https://github.com/user-attachments/assets/c8d7668c-57a1-4c55-acf1-6a37a505622c)
7. Submit new issue버튼을 클릭해 이슈를 업로드 합니다.

**📌branch 파는 방법**
1. 오른쪽에 있는 Development에서 Create branch 텍스트를 클릭합니다.
![image](https://github.com/user-attachments/assets/fb6bedea-0dc7-4810-8061-7f443005cbd8)
2. branch 이름을 통일합니다. 자동으로 작성된 이름의 맨 앞에 자신의 이름과 슬래시를 입력합니다. 아래의 예시처럼 작성하시면 됩니다.
![image](https://github.com/user-attachments/assets/8b9f401a-bfac-4eb0-b191-8e0a3924f5e4)
3. Create branch 버튼을 클릭하면 branch가 생성됩니다.
4. 안드로이드 스튜디오를 들어가서 git의 Fetch All Remotes를 클릭하면 생성된 branch를 확인할 수 있습니다.
![image](https://github.com/user-attachments/assets/5935cd5a-f05b-4d6f-bef5-731539830d2f)

## 확인하기(확인했으면 체크 부탁드립니다.)
- [x] 박기연
- [x] 박현주
- [x] 허나영

**Comment by gjsk132** [comment]
![image](https://github.com/user-attachments/assets/f186bffb-c016-4e21-8c56-72559953aa18)
인증샷
