### ISSUE TITLE
[TIP] 글자에 외곽선 넣기

### ISSUE THREAD

**Issue by gjsk132** [HICURE/HICURE#7]
### 작업 사항💡

xml에 따로 Stroke(외곽선)을 추가하는 코드가 없어서, 따로 커스텀으로 만들어뒀습니다.

사용하고 싶으시면 아래에 있는 코드 참고하시면 됩니다.

### Todo

1. TextView를 아래와 같이 변경한다.
2. `app:textStrokeColor`과 `app:testStrokeWidth`로 조정한다.

```xml
<com.example.hicure.OutLineTextView        

        // 이외의 원하는 코드

        app:textStrokeColor="@color/edge_blue"
        app:textStrokeWidth="18" />
```

### 기타사항

문제점이 하나 있는데, 너무 많이 Stroke값을 주면 양쪽 끝이 짤려서 안 보입니다.

( 딱히 상관없으면 괜찮은데, 너무 거슬리면 사용하지 않는 걸 추천...! )

**Comment by suhyun113** [comment]
![image](https://github.com/user-attachments/assets/e73077e0-74a1-45f6-ac45-39be9991c579)
우왕! 아직 미완성이지만 되어가는 즁~
